global:
  scrape_interval: 5s          # corto: las pruebas duran 60 s
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/alertas.yml

scrape_configs:
  - job_name: 'mariadb'
    static_configs:
      - {targets: ['exporter1:9104'], labels: {nodo: galera1}}
      - {targets: ['exporter2:9104'], labels: {nodo: galera2}}
      - {targets: ['exporter3:9104'], labels: {nodo: galera3}}

  - job_name: 'host'
    static_configs: [{targets: ['node-exporter:9100']}]

  - job_name: 'contenedores'
    static_configs: [{targets: ['cadvisor:8080']}]

  - job_name: 'haproxy'
    static_configs: [{targets: ['haproxy:8404']}]
